export const testselfData = {

    name: "zer",
    id: "5c56c3c1ae4c730506a86aa4",
    hp: 150,
    hand: [{
        "key": "Kayle",
        "name": "Kayle",
        "stats": {
            "armor": 26.88,
            "armorperlevel": 3.5,
            "attackdamage": 51,
            "attackdamageperlevel": 2.8,
            "attackrange": 125,
            "attackspeedoffset": -0.02,
            "attackspeedperlevel": 2.2,
            "crit": 0,
            "critperlevel": 0,
            "hp": 574.24,
            "hpperlevel": 93,
            "hpregen": 8.26,
            "hpregenperlevel": 0.75,
            "movespeed": 335,
            "mp": 322.2,
            "mpperlevel": 40,
            "mpregen": 6,
            "mpregenperlevel": 0.8,
            "spellblock": 30,
            "spellblockperlevel": 0
        },
        "title": "Justicière"
    },
    {
        "key": "Leblanc",
        "name": "LeBlanc",
        "stats": {
            "armor": 21.88,
            "armorperlevel": 3.5,
            "attackdamage": 54.88,
            "attackdamageperlevel": 3.5,
            "attackrange": 525,
            "attackspeedoffset": 0,
            "attackspeedperlevel": 1.4,
            "crit": 0,
            "critperlevel": 0,
            "hp": 516,
            "hpperlevel": 80,
            "hpregen": 7.4,
            "hpregenperlevel": 0.55,
            "movespeed": 340,
            "mp": 334,
            "mpperlevel": 50,
            "mpregen": 6,
            "mpregenperlevel": 0.8,
            "spellblock": 30,
            "spellblockperlevel": 0
        },
        "title": "Manipulatrice"
    },
    {
        "key": "Draven",
        "name": "Draven",
        "stats": {
            "armor": 25.544,
            "armorperlevel": 3.3,
            "attackdamage": 55.8,
            "attackdamageperlevel": 2.91,
            "attackrange": 550,
            "attackspeedoffset": -0.08,
            "attackspeedperlevel": 2.7,
            "crit": 0,
            "critperlevel": 0,
            "hp": 557.76,
            "hpperlevel": 82,
            "hpregen": 6.176,
            "hpregenperlevel": 0.7,
            "movespeed": 330,
            "mp": 360.56,
            "mpperlevel": 39,
            "mpregen": 8.042,
            "mpregenperlevel": 0.65,
            "spellblock": 30,
            "spellblockperlevel": 0
        },
        "title": "Glorieux exécuteur"
    }],
    deck: 15,
    cardPicked: false,
    board: [{
        "key": "Kayle",
        "name": "Kayle",
        "stats": {
            "armor": 26.88,
            "armorperlevel": 3.5,
            "attackdamage": 51,
            "attackdamageperlevel": 2.8,
            "attackrange": 125,
            "attackspeedoffset": -0.02,
            "attackspeedperlevel": 2.2,
            "crit": 0,
            "critperlevel": 0,
            "hp": 574.24,
            "hpperlevel": 93,
            "hpregen": 8.26,
            "hpregenperlevel": 0.75,
            "movespeed": 335,
            "mp": 322.2,
            "mpperlevel": 40,
            "mpregen": 6,
            "mpregenperlevel": 0.8,
            "spellblock": 30,
            "spellblockperlevel": 0
        },
        "title": "Justicière"
    },
    {
        "key": "Leblanc",
        "name": "LeBlanc",
        "stats": {
            "armor": 21.88,
            "armorperlevel": 3.5,
            "attackdamage": 54.88,
            "attackdamageperlevel": 3.5,
            "attackrange": 525,
            "attackspeedoffset": 0,
            "attackspeedperlevel": 1.4,
            "crit": 0,
            "critperlevel": 0,
            "hp": 516,
            "hpperlevel": 80,
            "hpregen": 7.4,
            "hpregenperlevel": 0.55,
            "movespeed": 340,
            "mp": 334,
            "mpperlevel": 50,
            "mpregen": 6,
            "mpregenperlevel": 0.8,
            "spellblock": 30,
            "spellblockperlevel": 0
        },
        "title": "Manipulatrice"
    },
    {
        "key": "Draven",
        "name": "Draven",
        "stats": {
            "armor": 25.544,
            "armorperlevel": 3.3,
            "attackdamage": 55.8,
            "attackdamageperlevel": 2.91,
            "attackrange": 550,
            "attackspeedoffset": -0.08,
            "attackspeedperlevel": 2.7,
            "crit": 0,
            "critperlevel": 0,
            "hp": 557.76,
            "hpperlevel": 82,
            "hpregen": 6.176,
            "hpregenperlevel": 0.7,
            "movespeed": 330,
            "mp": 360.56,
            "mpperlevel": 39,
            "mpregen": 8.042,
            "mpregenperlevel": 0.65,
            "spellblock": 30,
            "spellblockperlevel": 0
        },
        "title": "Glorieux exécuteur"
    }],
    turn: false
}

export const testopponentData = {
    name: "zer",
    id: "5c56c3c1ae4c730506a86aa4",
    hp: 150,
    hand: 4,
    deck: 15,
    cardPicked: false,
    board: [{
        "key": "Kayle",
        "name": "Kayle",
        "stats": {
            "armor": 26.88,
            "armorperlevel": 3.5,
            "attackdamage": 51,
            "attackdamageperlevel": 2.8,
            "attackrange": 125,
            "attackspeedoffset": -0.02,
            "attackspeedperlevel": 2.2,
            "crit": 0,
            "critperlevel": 0,
            "hp": 574.24,
            "hpperlevel": 93,
            "hpregen": 8.26,
            "hpregenperlevel": 0.75,
            "movespeed": 335,
            "mp": 322.2,
            "mpperlevel": 40,
            "mpregen": 6,
            "mpregenperlevel": 0.8,
            "spellblock": 30,
            "spellblockperlevel": 0
        },
        "title": "Justicière"
    },
    {
        "key": "Leblanc",
        "name": "LeBlanc",
        "stats": {
            "armor": 21.88,
            "armorperlevel": 3.5,
            "attackdamage": 54.88,
            "attackdamageperlevel": 3.5,
            "attackrange": 525,
            "attackspeedoffset": 0,
            "attackspeedperlevel": 1.4,
            "crit": 0,
            "critperlevel": 0,
            "hp": 516,
            "hpperlevel": 80,
            "hpregen": 7.4,
            "hpregenperlevel": 0.55,
            "movespeed": 340,
            "mp": 334,
            "mpperlevel": 50,
            "mpregen": 6,
            "mpregenperlevel": 0.8,
            "spellblock": 30,
            "spellblockperlevel": 0
        },
        "title": "Manipulatrice"
    },
    {
        "key": "Draven",
        "name": "Draven",
        "stats": {
            "armor": 25.544,
            "armorperlevel": 3.3,
            "attackdamage": 55.8,
            "attackdamageperlevel": 2.91,
            "attackrange": 550,
            "attackspeedoffset": -0.08,
            "attackspeedperlevel": 2.7,
            "crit": 0,
            "critperlevel": 0,
            "hp": 557.76,
            "hpperlevel": 82,
            "hpregen": 6.176,
            "hpregenperlevel": 0.7,
            "movespeed": 330,
            "mp": 360.56,
            "mpperlevel": 39,
            "mpregen": 8.042,
            "mpregenperlevel": 0.65,
            "spellblock": 30,
            "spellblockperlevel": 0
        },
        "title": "Glorieux exécuteur"
    }],
    turn: false
}